version: '3.3'
services:
  jenkins:
    build: .
    restart: unless-stopped
    privileged: true
    ports:
      - "443:8080"
    container_name: jenkins
    volumes:
      - jenkins-volume:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker
volumes:
  jenkins-volume:
